export const TOPICS_KNEE_SPORTS = [
  "ACL Tear",
  "Femoroacetabular Impingement (FAI)",
  "Meniscal Tears",
  "Patellar Instability",
  "Concussion",
  "Exercise Science",
  "Articular Cartilage Defects of Knee",
  "PCL Injury",
  "Osteochondritis Dissecans",
  "Infectious Diseases in Athletes",
  "Discoid Meniscus",
  "Female Athlete Conditions",
  "Cardiac Conditions in Athletes",
  "Exertional Compartment Syndrome",
  "Posterolateral Corner Injury",
  "Hip Arthroscopy",
  "Exertional Heat Illness",
  "Steroids & Stimulants",
  "Patellar Tendon Rupture",
  "Burners & Stingers",
  "Patellar Tendinitis",
  "Spontaneous Osteonecrosis of Knee",
  "Hamstring Injuries",
  "ASIS Avulsion Fracture",
  "Ear, Eye & Mouth Injuries",
  "Snapping Hip",
  "Neck Injuries in Athletes",
  "Quadriceps Tendon Rupture",
  "Hip Labral Tear",
  "Quadriceps Contusion",
  "Femoral Neck Stress Fracture",
  "Tibial Stress Fractures",
  "Meniscus Anatomy",
  "LCL Injury",
  "AIIS Avulsion",
  "MCL Injury",
  "Osgood–Schlatter Disease",
  "Visceral Blunt Trauma",
  "Iliotibial Band Syndrome",
  "Lateral Patellar Compression Syndrome",
  "Adductor Strain",
  "Rectus Femoris Strain",
  "Pulmonary Conditions in Athletes",
  "Knee Physical Examination",
  "Knee Imaging",
  "Proximal Tibiofibular Dislocation",
  "Chondromalacia Patella",
  "Plicae",
  "Athletic Pubalgia",
  "Osteitis Pubis",
  "Patellofemoral Joint",
  "Meniscal Cysts",
  "Quadriceps Tendonitis",
  "Prepatellar Bursitis",
  "Osteonecrosis of Knee",
  "Hip Pointer",
  "Piriformis Syndrome",
  "Popliteal Artery Entrapment",
  "Shin Splints",
  "Rib Stress Fracture",
  "Proximal Tibiofibular Ganglion Cyst",
];
