export const TOPICS_TRAUMA_INJURY_CARE = [
  "Ankle Fractures",
  "Acetabular Fractures",
  "Pelvic Ring Fractures",
  "Proximal Humerus Fractures",
  "Tibial Plateau Fractures",
  "Tibial Shaft Fractures",
  "Femoral Neck Fractures",
  "Femoral Shaft Fractures",
  "Calcaneus Fractures",
  "Trauma Evaluation, Resuscitation & Damage Control Orthopaedics (DCO)",
  "Humeral Shaft Fractures",
  "Distal Radius Fractures",
  "Amputations",
  "Intertrochanteric Fractures",
  "Distal Humerus Fractures",
  "Talar Neck Fractures",
  "Open Fractures Management",
  "Radial Head Fractures",
  "Proximal Third Tibia Fractures",
  "Leg Compartment Syndrome",
  "Terrible Triad Injury of Elbow",
  "Tibial Plafond (Pilon) Fractures",
  "Clavicle Fractures – Midshaft",
  "Knee Dislocation",
  "Subtrochanteric Fractures",
  "Distal Femur Fractures",
  "Radius & Ulna Shaft Fractures",
  "Osteomyelitis – Adult",
  "Elbow Dislocation",
  "Gun Shot Wounds",
  "Brachial Plexus Injuries",
  "Scapula Fractures",
  "Olecranon Fractures",
  "Septic Arthritis – Adult",
  "Domestic & Elder Abuse",
  "Necrotizing Fasciitis",
  "Capitellum Fractures",
  "Sternoclavicular Dislocation",
  "Coronoid Fractures",
  "Patella Fracture",
  "Sacral Fractures",
  "Humeral Shaft Nonunion",
  "Hip Dislocation",
  "Subtalar Dislocations",
  "Monteggia Fractures",
  "Hand & Forearm Compartment Syndrome",
  "Femoral Head Fractures",
  "Talus Fractures (Other than Neck)",
  "Wound & Hardware Infection",
  "Trauma Scoring Systems",
  "Clavicle Fractures – Distal",
  "Distal Radioulnar Joint (DRUJ) Injuries",
  "Scapulothoracic Dissociation",
  "Galeazzi Fractures",
  "SI Joint Dislocation & Crescent Fractures",
  "Femoral Neck Fracture Nonunion",
  "Geriatric Patient Trauma",
  "Isolated Ulnar Shaft Fracture",
  "Gustilo Classification",
  "Morel-Lavallée Lesion",
  "Distal Radius Malunion",
  "Adult Respiratory Distress Syndrome (ARDS)",
  "Flail Chest",
  "Foot Compartment Syndrome",
  "Neonatal Forearm Compartment Syndrome",
];
