export const TOPICS_RECON_ARTHROPLASTY = [
  "Prosthetic Joint Infection",
  "THA Periprosthetic Fracture",
  "THA Revision",
  "TKA Prosthesis Design",
  "Wear & Osteolysis",
  "THA Dislocation",
  "TKA Periprosthetic Fracture",
  "TKA Revision",
  "Knee Osteoarthritis",
  "Unicompartmental Knee Replacement",
  "TKA Polyethylene Wear",
  "TKA Patellofemoral Alignment",
  "THA Prosthesis Design",
  "Hip Osteonecrosis",
  "THA Stability Techniques",
  "Adult Hip Dysplasia",
  "High Tibial Osteotomy",
  "TKA Sagittal Plane Balancing",
  "THA Approaches",
  "THA Sciatic Nerve Palsy",
  "THA Complications",
  "Hip Resurfacing",
  "THA Trunnionosis",
  "TKA Extensor Mechanism Rupture",
  "THA Pseudotumor",
  "TKA Stiffness",
  "Knee Ligaments",
  "TKA Coronal Plane Balancing",
  "TKA Approaches",
  "TKA Instability",
  "Hip Osteoarthritis",
  "THA Iliopsoas Impingement",
  "TKA in Patella Baja",
  "THA Aseptic Loosening",
  "TKA Patellar Maltracking",
  "THA Implant Fixation",
  "THA Acetabular Screw Fixation",
  "TKA Peroneal Nerve Palsy",
  "TKA Wound Complications",
  "TKA Postoperative Care",
  "TKA Axial Alignment",
  "Hip Biomechanics",
  "Knee Biomechanics",
  "TKA Vascular Injury",
  "Adult Limb Deformity Correction",
  "Transient Osteoporosis of Hip",
  "THA Templating",
  "TKA Rehabilitation",
  "Patellar Clunk Syndrome",
  "THA Leg Length Discrepancy",
  "TKA Aseptic Loosening",
  "Arthroplasty Medical Optimization",
  "Hip Hemiarthroplasty Periprosthetic Fracture",
  "THA Rehabilitation",
  "TKA Patellar Loosening",
  "TKA Metal Hypersensitivity",
  "Hip Anatomy",
  "THA Postoperative Care",
  "THA Vascular Injury",
  "TKA Complications",
  "Hip Arthrodesis",
  "Adult Hip Physical Examination",
  "TKA Templating",
  "TKA Heterotopic Ossification",
  "TKA Kinematic Alignment",
];
