export const TOPICS_SPINE = [
  "Cervical Myelopathy",
  "Lumbar Disc Herniation",
  "Cervical Radiculopathy",
  "Lumbar Spinal Stenosis",
  "Spinal Cord Injuries",
  "Adult Spinal Deformity",
  "Adolescent Idiopathic Scoliosis",
  "Degenerative Spondylolisthesis",
  "Ankylosing Spondylitis",
  "Thoracolumbar Burst Fractures",
  "Odontoid Fractures",
  "Adult Isthmic Spondylolisthesis",
  "Osteoporotic Vertebral Compression Fractures",
  "Pediatric Spondylolysis & Spondylolisthesis",
  "Intervertebral Disc Disorders",
  "Incomplete Spinal Cord Injuries",
  "Congenital Scoliosis",
  "Halo Orthosis Immobilization",
  "Spinal Cord Monitoring",
  "Adult Pyogenic Vertebral Osteomyelitis",
  "Thoracic Disc Herniation",
  "Cervical Spine Trauma Evaluation",
  "Spinal Epidural Abscess",
  "Cervical Facet Dislocations & Fractures",
  "Cauda Equina Syndrome",
  "Low Back Pain",
  "Atlas Fractures & Transverse Ligament Injuries",
  "Diffuse Idiopathic Skeletal Hyperostosis (DISH)",
  "Juvenile Idiopathic Scoliosis",
  "Discogenic Back Pain",
  "Rheumatoid Cervical Spondylitis",
  "Infantile Idiopathic Scoliosis",
  "Lumbar Spine Anatomy",
  "Chance Fracture (Flexion–Distraction Injury)",
  "Scheuermann’s Kyphosis",
  "Synovial Facet Cyst",
  "Occipitocervical Instability",
  "Atlantoaxial Rotatory Displacement (AARD)",
  "Spine Biomechanics",
  "Spinal Cord Anatomy",
  "Spinal Tuberculosis",
  "Ossification of Posterior Longitudinal Ligament (OPLL)",
  "Vertebral Artery Injury",
  "Sacroiliac Joint Dysfunction",
  "Disk Space Infection – Pediatric",
  "Cervical Spine Anatomy",
  "Syrinx & Syringomyelia",
  "Subaxial Cervical Vertebral Body Fractures",
  "Pediatric Cervical Trauma Overview",
  "Neuromuscular Scoliosis",
  "Thoracic Spine Anatomy",
  "Cervical Disc Arthroplasty",
  "Spine Surgical Site Infections",
  "Cervical Lateral Mass Fracture Separation",
  "Lower Extremity Spine Examination",
  "Thoracolumbar Fracture–Dislocation",
  "Cervical Spondylosis",
  "Sacroiliitis",
  "Klippel–Feil Syndrome",
  "Congenital Muscular Torticollis",
  "Pathologic Scoliosis",
  "Neck & Upper Extremity Spine Examination",
  "Hangman’s Fracture",
  "Pseudosubluxation of Cervical Spine",
  "Atlantoaxial Instability",
  "Cerebral Palsy – Spinal Disorders",
  "Pediatric Spinal Cord Injury",
  "Spinal Cord Tumors",
  "Cervical Adjacent Segment Disease",
];
