export const TOPICS_SHOULDER_ELBOW = [
  "Rotator Cuff Tears",
  "Glenohumeral Arthritis",
  "Traumatic Anterior Shoulder Instability (TUBS)",
  "Total Shoulder Arthroplasty",
  "Reverse Shoulder Arthroplasty",
  "Medial Ulnar Collateral Ligament Injury",
  "Distal Biceps Tendon Avulsion",
  "Posterior Shoulder Instability & Dislocation",
  "Suprascapular Neuropathy",
  "Glenohumeral Internal Rotation Deficit (GIRD)",
  "Adhesive Capsulitis (Frozen Shoulder)",
  "Glenohumeral Joint Anatomy & Biomechanics",
  "Total Elbow Arthroplasty",
  "Rotator Cuff Arthropathy",
  "Acromioclavicular Joint Injury",
  "SLAP Lesions",
  "Posterolateral Rotatory Instability (PLRI)",
  "Multidirectional Shoulder Instability (MDI)",
  "Elbow Arthritis",
  "Internal Impingement",
  "Lateral Epicondylitis (Tennis Elbow)",
  "Scapular Winging",
  "Elbow Arthroscopy",
  "Little Leaguer’s Shoulder",
  "Shoulder Prosthetic Joint Infection",
  "Pectoralis Major Rupture",
  "Valgus Extension Overload",
  "Biceps Tendonitis",
  "Posterior Labral Tear",
  "Osteochondritis Dissecans of Elbow",
  "Shoulder Hemiarthroplasty",
  "Elbow Anatomy & Biomechanics",
  "Calcific Tendonitis",
  "Avascular Necrosis of Shoulder",
  "Elbow Stiffness",
  "Subacromial Impingement",
  "Phases of Throwing",
  "Biceps Subluxation",
  "Little League Elbow",
  "Revision Total Elbow Arthroplasty",
  "Brachial Neuritis",
  "Shoulder Arthroscopy",
  "Os Acromiale",
  "Shoulder Examination",
  "Quadrilateral Space Syndrome",
  "Acromioclavicular Arthritis",
  "Shoulder Imaging",
  "Triceps Rupture",
  "Medial Epicondylitis",
  "Neuropathic Shoulder Joint",
  "Shoulder Periprosthetic Fracture",
  "Olecranon Stress Fracture",
  "Elbow Physical Examination",
  "Sternoclavicular Joint Disorders",
  "Distal Clavicle Osteolysis",
  "Shoulder Arthrodesis",
  "Scapulothoracic Dyskinesis",
  "Scapulothoracic Joint Disorders",
  "Scapulothoracic Crepitus",
  "Thoracic Outlet Syndrome",
  "Latissimus Dorsi Rupture",
  "Luxatio Erecta",
];
