// FULL UNABRIDGED TOPIC LIST (placeholder pages; content to be added later)

export const EDUCATION_CATEGORIES = [
  {
    key: "trauma-injury-care",
    title: "Trauma & Injury Care",
    description: "Fractures, dislocations, infections, emergency red flags.",
  },
  {
    key: "spine",
    title: "Spine",
    description: "Neck and back conditions, deformity, infections, injuries.",
  },
  {
    key: "shoulder-elbow",
    title: "Shoulder & Elbow",
    description: "Rotator cuff, arthritis, instability, throwing injuries.",
  },
  {
    key: "knee-sports",
    title: "Knee & Sports",
    description: "ACL/meniscus and sports-related hip/knee injuries.",
  },
  {
    key: "pediatric-orthopaedics",
    title: "Pediatric Orthopaedics",
    description: "Children’s fractures, growth, hip, foot, neuromuscular.",
  },
  {
    key: "recon-arthroplasty",
    title: "Recon / Arthroplasty",
    description: "Hip/knee replacement topics, complications, rehab.",
  },
  {
    key: "hand-wrist",
    title: "Hand & Wrist",
    description: "Nerves, tendons, fractures, arthritis, congenital.",
  },
  {
    key: "foot-ankle",
    title: "Foot & Ankle",
    description: "Sprains, Achilles, bunions, diabetic foot, arthritis.",
  },
  {
    key: "pathology-orthopaedic-oncology",
    title: "Pathology (Orthopaedic Oncology)",
    description: "Bone/soft tissue tumours, staging, biopsy principles.",
  },
  {
    key: "basic-science-patient-knowledge",
    title: "Basic Science & Patient Knowledge",
    description: "Medicines, rehab, bone healing, ethics, safety.",
  },
  {
    key: "anatomy-patient-reference",
    title: "Anatomy (Patient Reference)",
    description: "Simple reference pages for common muscles and nerves.",
  },
];

export const EDUCATION_TOPICS_BY_CATEGORY = {
  "trauma-injury-care": [
    "Ankle Fractures",
    "Acetabular Fractures",
    "Pelvic Ring Fractures",
    "Proximal Humerus Fractures",
    "Tibial Plateau Fractures",
    "Tibial Shaft Fractures",
    "Femoral Neck Fractures",
    "Femoral Shaft Fractures",
    "Calcaneus Fractures",
    "Trauma Evaluation, Resuscitation & Damage Control Orthopaedics (DCO)",
    "Humeral Shaft Fractures",
    "Distal Radius Fractures",
    "Amputations",
    "Intertrochanteric Fractures",
    "Distal Humerus Fractures",
    "Talar Neck Fractures",
    "Open Fractures Management",
    "Radial Head Fractures",
    "Proximal Third Tibia Fractures",
    "Leg Compartment Syndrome",
    "Terrible Triad Injury of Elbow",
    "Tibial Plafond (Pilon) Fractures",
    "Clavicle Fractures – Midshaft",
    "Knee Dislocation",
    "Subtrochanteric Fractures",
    "Distal Femur Fractures",
    "Radius & Ulna Shaft Fractures",
    "Osteomyelitis – Adult",
    "Elbow Dislocation",
    "Gun Shot Wounds",
    "Brachial Plexus Injuries",
    "Scapula Fractures",
    "Olecranon Fractures",
    "Septic Arthritis – Adult",
    "Domestic & Elder Abuse",
    "Necrotizing Fasciitis",
    "Capitellum Fractures",
    "Sternoclavicular Dislocation",
    "Coronoid Fractures",
    "Patella Fracture",
    "Sacral Fractures",
    "Humeral Shaft Nonunion",
    "Hip Dislocation",
    "Subtalar Dislocations",
    "Monteggia Fractures",
    "Hand & Forearm Compartment Syndrome",
    "Femoral Head Fractures",
    "Talus Fractures (Other than Neck)",
    "Wound & Hardware Infection",
    "Trauma Scoring Systems",
    "Clavicle Fractures – Distal",
    "Distal Radioulnar Joint (DRUJ) Injuries",
    "Scapulothoracic Dissociation",
    "Galeazzi Fractures",
    "SI Joint Dislocation & Crescent Fractures",
    "Femoral Neck Fracture Nonunion",
    "Geriatric Patient Trauma",
    "Isolated Ulnar Shaft Fracture",
    "Gustilo Classification",
    "Morel-Lavallée Lesion",
    "Distal Radius Malunion",
    "Adult Respiratory Distress Syndrome (ARDS)",
    "Flail Chest",
    "Foot Compartment Syndrome",
    "Neonatal Forearm Compartment Syndrome",
  ],

  spine: [
    "Cervical Myelopathy",
    "Lumbar Disc Herniation",
    "Cervical Radiculopathy",
    "Lumbar Spinal Stenosis",
    "Spinal Cord Injuries",
    "Adult Spinal Deformity",
    "Adolescent Idiopathic Scoliosis",
    "Degenerative Spondylolisthesis",
    "Ankylosing Spondylitis",
    "Thoracolumbar Burst Fractures",
    "Odontoid Fractures",
    "Adult Isthmic Spondylolisthesis",
    "Osteoporotic Vertebral Compression Fractures",
    "Pediatric Spondylolysis & Spondylolisthesis",
    "Intervertebral Disc Disorders",
    "Incomplete Spinal Cord Injuries",
    "Congenital Scoliosis",
    "Halo Orthosis Immobilization",
    "Spinal Cord Monitoring",
    "Adult Pyogenic Vertebral Osteomyelitis",
    "Thoracic Disc Herniation",
    "Cervical Spine Trauma Evaluation",
    "Spinal Epidural Abscess",
    "Cervical Facet Dislocations & Fractures",
    "Cauda Equina Syndrome",
    "Low Back Pain",
    "Atlas Fractures & Transverse Ligament Injuries",
    "Diffuse Idiopathic Skeletal Hyperostosis (DISH)",
    "Juvenile Idiopathic Scoliosis",
    "Discogenic Back Pain",
    "Rheumatoid Cervical Spondylitis",
    "Infantile Idiopathic Scoliosis",
    "Lumbar Spine Anatomy",
    "Chance Fracture (Flexion–Distraction Injury)",
    "Scheuermann’s Kyphosis",
    "Synovial Facet Cyst",
    "Occipitocervical Instability",
    "Atlantoaxial Rotatory Displacement (AARD)",
    "Spine Biomechanics",
    "Spinal Cord Anatomy",
    "Spinal Tuberculosis",
    "Ossification of Posterior Longitudinal Ligament (OPLL)",
    "Vertebral Artery Injury",
    "Sacroiliac Joint Dysfunction",
    "Disk Space Infection – Pediatric",
    "Cervical Spine Anatomy",
    "Syrinx & Syringomyelia",
    "Subaxial Cervical Vertebral Body Fractures",
    "Pediatric Cervical Trauma Overview",
    "Neuromuscular Scoliosis",
    "Thoracic Spine Anatomy",
    "Cervical Disc Arthroplasty",
    "Spine Surgical Site Infections",
    "Cervical Lateral Mass Fracture Separation",
    "Lower Extremity Spine Examination",
    "Thoracolumbar Fracture–Dislocation",
    "Cervical Spondylosis",
    "Sacroiliitis",
    "Klippel–Feil Syndrome",
    "Congenital Muscular Torticollis",
    "Pathologic Scoliosis",
    "Neck & Upper Extremity Spine Examination",
    "Hangman’s Fracture",
    "Pseudosubluxation of Cervical Spine",
    "Atlantoaxial Instability",
    "Cerebral Palsy – Spinal Disorders",
    "Pediatric Spinal Cord Injury",
    "Spinal Cord Tumors",
    "Cervical Adjacent Segment Disease",
  ],

  "shoulder-elbow": [
    "Rotator Cuff Tears",
    "Glenohumeral Arthritis",
    "Traumatic Anterior Shoulder Instability (TUBS)",
    "Total Shoulder Arthroplasty",
    "Reverse Shoulder Arthroplasty",
    "Medial Ulnar Collateral Ligament Injury",
    "Distal Biceps Tendon Avulsion",
    "Posterior Shoulder Instability & Dislocation",
    "Suprascapular Neuropathy",
    "Glenohumeral Internal Rotation Deficit (GIRD)",
    "Adhesive Capsulitis (Frozen Shoulder)",
    "Glenohumeral Joint Anatomy & Biomechanics",
    "Total Elbow Arthroplasty",
    "Rotator Cuff Arthropathy",
    "Acromioclavicular Joint Injury",
    "SLAP Lesions",
    "Posterolateral Rotatory Instability (PLRI)",
    "Multidirectional Shoulder Instability (MDI)",
    "Elbow Arthritis",
    "Internal Impingement",
    "Lateral Epicondylitis (Tennis Elbow)",
    "Scapular Winging",
    "Elbow Arthroscopy",
    "Little Leaguer’s Shoulder",
    "Shoulder Prosthetic Joint Infection",
    "Pectoralis Major Rupture",
    "Valgus Extension Overload",
    "Biceps Tendonitis",
    "Posterior Labral Tear",
    "Osteochondritis Dissecans of Elbow",
    "Shoulder Hemiarthroplasty",
    "Elbow Anatomy & Biomechanics",
    "Calcific Tendonitis",
    "Avascular Necrosis of Shoulder",
    "Elbow Stiffness",
    "Subacromial Impingement",
    "Phases of Throwing",
    "Biceps Subluxation",
    "Little League Elbow",
    "Revision Total Elbow Arthroplasty",
    "Brachial Neuritis",
    "Shoulder Arthroscopy",
    "Os Acromiale",
    "Shoulder Examination",
    "Quadrilateral Space Syndrome",
    "Acromioclavicular Arthritis",
    "Shoulder Imaging",
    "Triceps Rupture",
    "Medial Epicondylitis",
    "Neuropathic Shoulder Joint",
    "Shoulder Periprosthetic Fracture",
    "Olecranon Stress Fracture",
    "Elbow Physical Examination",
    "Sternoclavicular Joint Disorders",
    "Distal Clavicle Osteolysis",
    "Shoulder Arthrodesis",
    "Scapulothoracic Dyskinesis",
    "Scapulothoracic Joint Disorders",
    "Scapulothoracic Crepitus",
    "Thoracic Outlet Syndrome",
    "Latissimus Dorsi Rupture",
    "Luxatio Erecta",
  ],

  "knee-sports": [
    "ACL Tear",
    "Femoroacetabular Impingement (FAI)",
    "Meniscal Tears",
    "Patellar Instability",
    "Concussion",
    "Exercise Science",
    "Articular Cartilage Defects of Knee",
    "PCL Injury",
    "Osteochondritis Dissecans",
    "Infectious Diseases in Athletes",
    "Discoid Meniscus",
    "Female Athlete Conditions",
    "Cardiac Conditions in Athletes",
    "Exertional Compartment Syndrome",
    "Posterolateral Corner Injury",
    "Hip Arthroscopy",
    "Exertional Heat Illness",
    "Steroids & Stimulants",
    "Patellar Tendon Rupture",
    "Burners & Stingers",
    "Patellar Tendinitis",
    "Spontaneous Osteonecrosis of Knee",
    "Hamstring Injuries",
    "ASIS Avulsion Fracture",
    "Ear, Eye & Mouth Injuries",
    "Snapping Hip",
    "Neck Injuries in Athletes",
    "Quadriceps Tendon Rupture",
    "Hip Labral Tear",
    "Quadriceps Contusion",
    "Femoral Neck Stress Fracture",
    "Tibial Stress Fractures",
    "Meniscus Anatomy",
    "LCL Injury",
    "AIIS Avulsion",
    "MCL Injury",
    "Osgood–Schlatter Disease",
    "Visceral Blunt Trauma",
    "Iliotibial Band Syndrome",
    "Lateral Patellar Compression Syndrome",
    "Adductor Strain",
    "Rectus Femoris Strain",
    "Pulmonary Conditions in Athletes",
    "Knee Physical Examination",
    "Knee Imaging",
    "Proximal Tibiofibular Dislocation",
    "Chondromalacia Patella",
    "Plicae",
    "Athletic Pubalgia",
    "Osteitis Pubis",
    "Patellofemoral Joint",
    "Meniscal Cysts",
    "Quadriceps Tendonitis",
    "Prepatellar Bursitis",
    "Osteonecrosis of Knee",
    "Hip Pointer",
    "Piriformis Syndrome",
    "Popliteal Artery Entrapment",
    "Shin Splints",
    "Rib Stress Fracture",
    "Proximal Tibiofibular Ganglion Cyst",
  ],

  "pediatric-orthopaedics": [
    "Supracondylar Fracture – Pediatric",
    "Pediatric Osteomyelitis",
    "Developmental Dysplasia of Hip",
    "Slipped Capital Femoral Epiphysis",
    "Pediatric Abuse",
    "Pediatric Femoral Shaft Fracture",
    "Pediatric Hip Septic Arthritis",
    "Tarsal Coalition",
    "Neurofibromatosis",
    "Clubfoot",
    "Leg Length Discrepancy",
    "Obstetric Brachial Plexopathy",
    "Distal Femoral Physeal Fractures",
    "Charcot–Marie–Tooth Disease",
    "Duchenne Muscular Dystrophy",
    "Achondroplasia",
    "Osteogenesis Imperfecta",
    "Infantile Blount Disease",
    "Physeal Considerations",
    "Medial Epicondyle Fracture – Pediatric",
    "Cavovarus Foot",
    "Proximal Femur Fracture – Pediatric",
    "Tibial Eminence Fracture",
    "Distal Radius Fracture – Pediatric",
    "Lateral Condyle Fracture – Pediatric",
    "Tibial Tubercle Fracture",
    "Cerebral Palsy – General",
    "Myelodysplasia",
    "Congenital Vertical Talus",
    "Spinal Muscular Atrophy",
    "Cerebral Palsy – Gait Disorders",
    "Marfan Syndrome",
    "Osteopetrosis",
    "Tibial Shaft Fracture – Pediatric",
    "Both Bone Forearm Fracture – Pediatric",
    "Cerebral Palsy – Hip Disorders",
    "Pediatric Ankle Fractures",
    "Accessory Navicular",
    "Kohler Disease",
    "Perthes Disease",
    "Lyme Disease",
    "Distal Humerus Physeal Separation",
    "Radial Head & Neck Fracture – Pediatric",
    "Monteggia Fracture – Pediatric",
    "Proximal Tibia Metaphyseal Fracture",
    "Tillaux Fracture",
    "Posteromedial Tibial Bowing",
    "Mucopolysaccharidoses",
    "Proximal Humerus Fracture – Pediatric",
    "Sever Disease",
    "Pediatric Trauma Evaluation",
    "Pediatric Pelvic Fractures",
    "Adolescent Blount Disease",
    "Fibular Deficiency",
    "Congenital Pseudoarthrosis of Tibia",
    "Femoral Anteversion",
    "Internal Tibial Torsion",
    "Flexible Flatfoot",
    "Arthrogryposis",
    "Down Syndrome",
    "Pediatric Humeral Shaft Fracture",
    "Pediatric Elbow Dislocation",
    "Triplane Fracture",
    "Cleidocranial Dysplasia",
    "Transient Synovitis of Hip",
    "Sprengel Deformity",
    "Proximal Femoral Focal Deficiency",
    "Multiple Epiphyseal Dysplasia",
    "Diastrophic Dysplasia",
    "Distal Clavicle Physeal Fracture",
    "Pediatric Olecranon Fracture",
    "Proximal Tibia Epiphyseal Fracture",
    "Sacral Agenesis",
    "Congenital Knee Dislocation",
    "Bipartite Patella",
    "Genu Valgum",
    "Polydactyly of Foot",
    "Nursemaid’s Elbow",
    "Pediatric Traumatic Hip Dislocation",
    "Coxa Vara",
    "Tibial Deficiency",
    "Metatarsus Adductus",
    "Calcaneovalgus Foot",
    "Congenital Curly Toe",
    "Friedreich Ataxia",
    "Larsen Syndrome",
    "Spondyloepiphyseal Dysplasia",
    "Beckwith–Wiedemann Syndrome",
    "Epiphyseal Bracket",
    "Pediatric Clavicle Shaft Fracture",
    "Pediatric SI Joint Infection",
    "CRMO",
    "Congenital Pseudoarthrosis of Clavicle",
    "Congenital Patellar Dislocation",
    "Popliteal Cyst – Pediatric",
    "Syndactyly of Toes",
    "Overlapping Toe",
    "Brachymetatarsia",
    "Local Gigantism",
    "Rett Syndrome",
    "Trevor Disease",
    "Bladder Exstrophy",
    "Gaucher Disease",
    "Pediatric Psoas Abscess",
    "Congenital Popliteal Webbing",
  ],

  "recon-arthroplasty": [
    "Prosthetic Joint Infection",
    "THA Periprosthetic Fracture",
    "THA Revision",
    "TKA Prosthesis Design",
    "Wear & Osteolysis",
    "THA Dislocation",
    "TKA Periprosthetic Fracture",
    "TKA Revision",
    "Knee Osteoarthritis",
    "Unicompartmental Knee Replacement",
    "TKA Polyethylene Wear",
    "TKA Patellofemoral Alignment",
    "THA Prosthesis Design",
    "Hip Osteonecrosis",
    "THA Stability Techniques",
    "Adult Hip Dysplasia",
    "High Tibial Osteotomy",
    "TKA Sagittal Plane Balancing",
    "THA Approaches",
    "THA Sciatic Nerve Palsy",
    "THA Complications",
    "Hip Resurfacing",
    "THA Trunnionosis",
    "TKA Extensor Mechanism Rupture",
    "THA Pseudotumor",
    "TKA Stiffness",
    "Knee Ligaments",
    "TKA Coronal Plane Balancing",
    "TKA Approaches",
    "TKA Instability",
    "Hip Osteoarthritis",
    "THA Iliopsoas Impingement",
    "TKA in Patella Baja",
    "THA Aseptic Loosening",
    "TKA Patellar Maltracking",
    "THA Implant Fixation",
    "THA Acetabular Screw Fixation",
    "TKA Peroneal Nerve Palsy",
    "TKA Wound Complications",
    "TKA Postoperative Care",
    "TKA Axial Alignment",
    "Hip Biomechanics",
    "Knee Biomechanics",
    "TKA Vascular Injury",
    "Adult Limb Deformity Correction",
    "Transient Osteoporosis of Hip",
    "THA Templating",
    "TKA Rehabilitation",
    "Patellar Clunk Syndrome",
    "THA Leg Length Discrepancy",
    "TKA Aseptic Loosening",
    "Arthroplasty Medical Optimization",
    "Hip Hemiarthroplasty Periprosthetic Fracture",
    "THA Rehabilitation",
    "TKA Patellar Loosening",
    "TKA Metal Hypersensitivity",
    "Hip Anatomy",
    "THA Postoperative Care",
    "THA Vascular Injury",
    "TKA Complications",
    "Hip Arthrodesis",
    "Adult Hip Physical Examination",
    "TKA Templating",
    "TKA Heterotopic Ossification",
    "TKA Kinematic Alignment",
  ],

  "hand-wrist": [
    "Carpal Tunnel Syndrome",
    "Peripheral Nerve Injury & Repair",
    "Flexor Tendon Injuries",
    "Scaphoid Fracture",
    "Fingertip Amputation & Finger Flaps",
    "Phalanx Fractures",
    "Basilar Thumb Arthritis",
    "Kienbock Disease",
    "Cubital Tunnel Syndrome",
    "Metacarpal Fractures",
    "Phalanx Dislocations",
    "Dupuytren Disease",
    "Replantation",
    "SLAC Wrist",
    "Extremity Flap Reconstruction",
    "Ganglion Cysts",
    "Perilunate Dislocation",
    "Radial Clubhand",
    "Hook of Hamate Fracture",
    "DIP & PIP Joint Arthritis",
    "MCP Dislocations",
    "Ulnar Tunnel Syndrome",
    "Pyogenic Flexor Tenosynovitis",
    "Mallet Finger",
    "Scapholunate Ligament Injury",
    "TFCC Injury",
    "Scaphoid Nonunion",
    "Quadriga Effect",
    "Constrictive Ring Syndrome",
    "High Pressure Injection Injury",
    "Flexor Pulley System",
    "Jersey Finger",
    "De Quervain Tenosynovitis",
    "Extensor Tendon Injuries",
    "Tendon Transfer Principles",
    "Giant Cell Tumor of Tendon Sheath",
    "SNAC Wrist",
    "AIN Compression Syndrome",
    "PIN Compression Syndrome",
    "Radial Tunnel Syndrome",
    "Trigger Finger",
    "Sagittal Band Rupture",
    "Base of Thumb Fractures",
    "Thumb Collateral Ligament Injury",
    "Polydactyly of Hand",
    "Congenital Trigger Thumb",
    "Raynaud Syndrome",
    "Frostbite",
    "Wrist Ligaments",
    "Wrist Arthroscopy",
    "Snapping ECU",
    "Ulnocarpal Abutment Syndrome",
    "Congenital Radioulnar Synostosis",
    "Hypothenar Hammer Syndrome",
    "Thumb CMC Dislocation",
    "Seymour Fracture",
    "Intrinsic Plus Hand",
    "Intersection Syndrome",
    "Madelung Deformity",
    "Poland Syndrome",
    "Thumb Hypoplasia",
    "Dog & Cat Bites",
    "MCP Joint Arthritis",
    "Claw Hand",
    "Pronator Syndrome",
    "Ulnar Styloid Impaction",
    "Wrist Arthritis",
    "Congenital Radial Head Dislocation",
    "Apert Syndrome",
    "Hand Blood Supply",
    "Hand Physical Examination",
    "Boutonniere Deformity",
    "Swan Neck Deformity",
    "CIND",
    "Ulnar Variance",
    "Gymnast Wrist",
    "Camptodactyly",
    "Felon",
    "Human Bite",
    "Nail Bed Injury",
    "Pisiform Fracture",
    "Nerve Conduction Studies",
    "Subclavian Artery Thrombosis",
    "Finger Ligaments",
    "Extensor Compartments",
    "Lumbrical Plus Finger",
    "Wartenberg Syndrome",
    "FCR Tendinitis",
    "Digital Collateral Ligament Injury",
    "Lunotriquetral Ligament Injury",
    "Preiser Disease",
    "Skin Grafting",
    "Cleft Hand",
    "Syndactyly",
    "Macrodactyly",
    "Congenital Clasped Thumb",
    "Epidermal Inclusion Cyst",
    "Buerger Disease",
    "Deep Space Hand Infections",
    "Atypical Mycobacterial Infection",
    "Digital Artery Aneurysm",
    "Wrist Trauma Radiographic Evaluation",
    "Triquetrum Fracture",
    "Radiocarpal Fracture Dislocation",
  ],

  "foot-ankle": [
    "Hallux Valgus",
    "Posterior Tibial Tendon Insufficiency",
    "Ankle Sprain",
    "Lisfranc Injury",
    "Hallux Rigidus",
    "Achilles Tendon Rupture",
    "Diabetic Foot Ulcers",
    "Peroneal Tendon Tears",
    "5th Metatarsal Base Fracture",
    "Foot Muscle Forces & Deformities",
    "Charcot Foot",
    "Ankle Arthrodesis",
    "Ankle Arthritis",
    "Achilles Tendonitis",
    "Osteochondral Lesions of Talus",
    "Bunionette Deformity",
    "Syndesmotic Injury",
    "Morton Neuroma",
    "Ankle Arthroscopy",
    "Ankle Ligaments",
    "Claw Toe",
    "Plantar Fasciitis",
    "Foot Puncture Wounds",
    "Navicular Fractures",
    "Tarsal Tunnel Syndrome",
    "Total Ankle Arthroplasty",
    "Freiberg Disease",
    "Metatarsal Fractures",
    "Midfoot Arthritis",
    "Leg Nerve Entrapment Syndromes",
    "Lower Extremity Ossicles",
    "Gait Cycle",
    "Sesamoid Injuries",
    "MTP Dislocations",
    "FHL Tendon Injury",
    "Turf Toe",
    "Foot Nerves",
    "Foot Anatomy & Biomechanics",
    "Hallux Varus",
    "Hammer Toe",
    "Tibiotalar Impingement",
    "Anterior Tibialis Tendon Rupture",
    "2nd MTP Synovitis",
    "Poliomyelitis",
    "Orthotics",
    "Spastic Equinovarus Deformity",
    "Deep Peroneal Nerve Entrapment",
    "Blood Supply to Foot",
  ],

  "pathology-orthopaedic-oncology": [
    "Metastatic Bone Disease – Extremity",
    "Chondrosarcoma",
    "Osteosarcoma",
    "Giant Cell Tumor",
    "Soft Tissue Sarcoma",
    "Osteochondroma",
    "Metastatic Spine Disease",
    "Ewing Sarcoma",
    "Enchondroma",
    "Pigmented Villonodular Synovitis",
    "Paget Disease of Bone",
    "Unicameral Bone Cyst",
    "Liposarcoma",
    "Osteoid Osteoma",
    "Aneurysmal Bone Cyst",
    "Synovial Sarcoma",
    "Non-Ossifying Fibroma",
    "Fibrous Dysplasia",
    "Chondroblastoma",
    "Biopsy Principles",
    "Multiple Myeloma",
    "Heterotopic Ossification",
    "Periosteal Osteosarcoma",
    "Myositis Ossificans",
    "Parosteal Osteosarcoma",
    "Lymphoma of Bone",
    "Schwannoma",
    "Lipoma",
    "Eosinophilic Granuloma",
    "Adamantinoma",
    "Desmoid Tumor",
    "Chordoma",
    "Undifferentiated Pleomorphic Sarcoma",
    "Soft Tissue Hemangioma",
    "Squamous Cell Carcinoma",
    "Chondromyxoid Fibroma",
    "Osteofibrous Dysplasia",
    "Synovial Chondromatosis",
    "Epithelioid Sarcoma",
    "Impending Fracture",
    "Chemotherapy",
    "Radiation Therapy",
    "Rhabdomyosarcoma",
    "Melanoma",
    "Bone Tumor Staging",
    "Pleomorphic Sarcoma of Bone",
    "Neurofibroma",
    "Tumoral Calcinosis",
    "Osteoblastoma",
    "Telangiectatic Osteosarcoma",
    "Hemangioma",
    "Melorheostosis",
    "Malignant Peripheral Nerve Sheath Tumor",
    "Dermatofibrosarcoma Protuberans",
    "Glomus Tumor",
    "Periosteal Chondroma",
    "Leiomyosarcoma",
    "Plantar Fibromatosis",
    "Bone Infarct",
    "Intramuscular Myxoma",
    "Leukemia",
    "Nodular Fasciitis",
    "Angiosarcoma",
    "Focal Fibrocartilaginous Dysplasia",
    "Neuroblastoma",
  ],

  "basic-science-patient-knowledge": [
    "Legal Issues in Orthopaedics",
    "Statistics Explained",
    "Osteopenia & Osteoporosis",
    "Rheumatoid Arthritis",
    "Material Properties",
    "Orthopaedic Implants",
    "Bone Grafting",
    "Articular Cartilage",
    "Fracture Healing",
    "Antibiotics",
    "Anticoagulants",
    "Ethics in Medicine",
    "DVT & PE Prevention",
    "Rickets",
    "Bisphosphonates",
    "Clinical Trials",
    "Complex Regional Pain Syndrome",
    "Bone Cells",
    "Bone Signaling",
    "Genetic Disorders",
    "Gout",
    "Rehabilitation & Prosthetics",
    "Anaesthesia",
    "Bone Growth Factors",
    "Anti-inflammatory Drugs",
    "Evidence-Based Medicine",
    "Tendons",
    "Muscle Biology",
    "Nonunion",
    "Occupational Health",
    "Outcome Measures",
    "Bone Remodeling",
    "Genetic Pearls",
    "Pain Medications",
    "Juvenile Idiopathic Arthritis",
    "Sickle Cell Disease",
    "Molecular Biology",
    "Endochondral Ossification",
    "Medical Billing",
    "Ligaments",
    "Surgical Antibiotic Prophylaxis",
    "PRP",
    "Hemophilia",
    "Collagen",
    "Psoriatic Arthritis",
    "Fat Embolism Syndrome",
    "Immunology",
    "Embryology",
    "Vitamin D & PTH",
    "Renal Osteodystrophy",
    "Hyperparathyroidism",
    "Bone Metabolism",
    "Cartilage Biology",
    "Hypophosphatasia",
    "DVT",
    "Pseudogout",
    "Bone Matrix",
    "Synovial Fluid",
    "Hemophilic Arthropathy",
    "Blood Transfusion",
    "Informed Consent",
    "Bone Circulation",
    "Ochronosis",
    "Lead Toxicity",
    "Intramembranous Ossification",
    "Hypoparathyroidism",
    "Scurvy",
    "ALS",
    "Structural Properties",
    "Myasthenia Gravis",
    "Bioabsorbable Materials",
    "Multiple Sclerosis",
    "Scleroderma",
    "Career Development",
  ],

  "anatomy-patient-reference": [
    "Sciatic Nerve",
    "Subscapularis",
    "Radial Nerve",
    "Posterior Interosseous Nerve",
    "Axillary Nerve",
    "Biceps Brachii",
    "Psoas Muscle",
    "Adductor Longus",
    "Piriformis",
    "Peroneus Brevis",
    "Median Nerve",
    "Ulnar Nerve",
    "Lumbosacral Plexus",
    "Superficial Peroneal Nerve",
    "Pectoralis Major",
    "Teres Major",
    "Brachialis",
    "Flexor Pollicis Longus",
    "Extensor Indicis Proprius",
    "Abductor Digiti Minimi",
    "Lumbricals",
    "Brachial Plexus",
    "Iliacus",
    "Sartorius",
    "Gluteus Medius",
    "Semimembranosus",
    "Biceps Femoris (Short Head)",
    "Obturator Internus",
    "Extensor Digitorum Longus",
    "Peroneus Tertius",
    "Popliteus",
    "Flexor Hallucis Longus",
    "Musculocutaneous Nerve",
    "Anterior Interosseous Nerve",
    "Femoral Nerve",
    "Quadrangular Space",
  ],
};

export function topicToSlug(topic) {
  return (topic || "")
    .trim()
    .toLowerCase()
    .replaceAll("&", "and")
    .replaceAll(/\(|\)|\.|,/g, "")
    .replaceAll(/\s+–\s+|\s+—\s+/g, "-")
    .replaceAll(/\s+/g, "-")
    .replaceAll(/[^a-z0-9-]/g, "")
    .replaceAll(/-+/g, "-")
    .replaceAll(/^-|-$/g, "");
}

export function categoryKeyToTitle(key) {
  const c = EDUCATION_CATEGORIES.find((x) => x.key === key);
  return c?.title || key;
}
