import { getProductBySlug } from '@/lib/data';
import { notFound } from 'next/navigation';

export async function GET(
  request: Request,
  { params }: { params: Promise<{ slug: string }> }
) {
  const { slug } = await params;
  const rawProduct = await getProductBySlug(slug);

  if (!rawProduct) {
    return new Response('Product not found.', { status: 404 });
  }

  // Bypass type constraints for Next.js 15
  const product = rawProduct as any;

  // Format specifications into markdown
  let specsMarkdown = '';
  if (product.technical_specifications && Object.keys(product.technical_specifications).length > 0) {
    specsMarkdown = `\n## Technical Specifications\n`;
    for (const [key, value] of Object.entries(product.technical_specifications)) {
      specsMarkdown += `- **${key}**: ${value}\n`;
    }
  }

  // Format clinical indications
  let indicationsMarkdown = '';
  if (product.clinical_indications && product.clinical_indications.length > 0) {
    indicationsMarkdown = `\n## Clinical Indications\n`;
    product.clinical_indications.forEach((ind: string) => {
      indicationsMarkdown += `- ${ind}\n`;
    });
  }

  // Build the complete Markdown document optimized for LLM ingestion
  const markdownContent = `
# ${product.product_name_display}

**Manufacturer**: ${product.manufacturer || 'Meril Life Sciences'}
**Distributor**: Agile Healthcare (Telangana Master Franchise)
**Division**: ${product.division_canonical}
**Category**: ${product.category}
**Material**: ${product.materials_canonical || product.material_canonical || 'N/A'}
**SKU/REF**: ${product.sku_code || 'MRL-GEN'}

## Clinical Summary
${product.description_live || product.description_shadow || 'No description available.'}
${specsMarkdown}${indicationsMarkdown}

## Ordering & Logistics
This medical device is distributed by Agile Healthcare across all 33 districts of Telangana, India.
- **Availability**: Immediate dispatch for emergency OTs.
- **Support**: +91 74162 16262 (24/7 Logistics)
- **Official URL**: https://agilehealthcare.in/catalog/products/${product.slug}

---
*Document generated by Agile Healthcare AEO Engine for AI Web Crawlers.*
  `.trim();

  return new Response(markdownContent, {
    status: 200,
    headers: {
      'Content-Type': 'text/markdown; charset=utf-8',
      'Cache-Control': 'public, s-maxage=86400, stale-while-revalidate=43200',
    },
  });
}
